name: TileDB-SOMA build=Debug
on:
  workflow_dispatch:
    inputs:
      runs-on:
        description: 'Github Actions runner'
        default: 'ubuntu-latest'
        type: choice
        options:
          - 'ubuntu-latest'
          - 'macos-latest'
          - 'windows-latest'
          - 'macos-latest-xlarge'
      org:
        description: 'Org to clone TileDB-SOMA from'
        required: true
        default: 'TileDB-Inc'
      ref:
        description: 'Branch or tag to checkout'
        default: 'main'
        type: string
jobs:
  build:
    runs-on: ${{ inputs.runs-on }}
    steps:
      - name: Clone ${{ inputs.org }}/TileDB-SOMA@${{ inputs.ref }}
        uses: actions/checkout@v4
        with:
          repository: ${{ inputs.org }}/TileDB-SOMA
          ref: ${{ inputs.ref }}
      - uses: actions/setup-python@v5
        with:
          python-version: 3.11.8
      - name: Synthesize version
        run: |
          echo "1.9.0rc0" > apis/python/RELEASE-VERSION
      - run: make install build=Debug
