name: Test cellxgene_census_builder/tests/test_builder.py
on:
  workflow_dispatch:
    inputs:
      runs-on:
        description: 'Select a runner ("macos-latest" = Intel, "macos-latest-xlarge" = M1)'
        default: ubuntu-latest
        type: choice
        options:
          - macos-latest
          - macos-latest-xlarge
          - ubuntu-latest
          # - windows-latest
      ref:
        description: 'TileDB-SOMA branch or tag clone/install/test (leave blank to install latest version from PyPI)'
        default: 'main'
      checkout:
        description: 'Checkout TileDB-SOMA at this commit or ref'
jobs:
  build:
    name: repro (${{ inputs.runs-on || 'ubuntu-latest' }})
    runs-on: ${{ inputs.runs-on || 'ubuntu-latest' }}
    steps:
      - name: 'Debug: `github` context'
        run: echo "${{ toJSON(github.event) }}"
      - name: Clone census
        uses: actions/checkout@v4
        with:
          repository: chanzuckerberg/cellxgene-census
          ref: main
          path: census
      - uses: actions/setup-python@v5
        with:
          python-version: 3.11.8
      - name: Install cellxgene_census_builder
        run: |
          pip install -e census/tools/cellxgene_census_builder
          pip list
          python -c 'import cellxgene_census_builder'
      - name: Clone TileDB-SOMA@${{ inputs.ref || 'main' }}
        uses: actions/checkout@v4
        with:
          repository: single-cell-data/TileDB-SOMA
          ref: ${{ inputs.ref || 'main' }}
          fetch-depth: ${{ inputs.checkout == '' && 1 || 0 }}
          path: tiledbsoma
      - name: Checkout ${{ inputs.checkout }}
        if: inputs.checkout != ''
        working-directory: tiledbsoma
        run: |
          git checkout ${{ inputs.checkout }}
          git log -1
      - name: Install TileDB-SOMA
        run: pip install -e tiledbsoma/apis/python pytest
      - name: Show package versions
        run: |
          uname -a
          pip list
          python -c 'import tiledbsoma; tiledbsoma.show_package_versions()'
          python tiledbsoma/scripts/show-versions.py
      - name: Run census test
        working-directory: census/tools/cellxgene_census_builder
        run: pytest tests/test_builder.py
