name: Build and test
on:
  workflow_dispatch:
    inputs:
      ref:
        description: 'Branch or tag to build'
        required: true
        default: 'main'
jobs:
  test:
    strategy:
      matrix:
        os: [ubuntu-latest]
        py: ["3.9", "3.10", "3.11", "3.12"]
      fail-fast: false
    name: ${{ matrix.os }} x Python ${{ matrix.py }}
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.py }}
      - uses: actions/checkout@v4
        with:
          repository: 'single-cell-data/TileDB-SOMA'
          fetch-depth: 0
      - run: git checkout ${{ github.event.inputs.ref }}
      - run: make install build=Debug
      - run: make data
      - run: pip install -e apis/python[dev]
      - run: |
          cd apis/python
          pytest tests