name: TileDB-SOMA Python CI (macos-12, coverage)
on:
  workflow_dispatch:
    inputs:
      os:
        description: 'OS'
        type: 'choice'
        options:
          - 'macos-12'
        default: 'macos-12'
      python-version:
        description: 'Python version'
        default: '3.11'
jobs:
  build:
    runs-on: ${{ inputs.os }}
    steps:
      - name: MacOS CPU info
        run: sysctl -a | grep cpu
      - name: Select XCode version
        uses: maxim-lobanov/setup-xcode@v1
        with:
          # Pending https://github.com/actions/runner-images/issues/6350
          xcode-version: '13.4'
      - name: Checkout TileDB-SOMA
        uses: actions/checkout@v4
        with:
          repository: single-cell-data/TileDB-SOMA
          fetch-depth: 0  # ensure we get all tags to inform package version determination
      - name: Set up Python ${{ inputs.python-version }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ inputs.python-version }}
          cache: pip
          cache-dependency-path: ./apis/python/setup.py
      - name: Install tiledbsoma
        run: python -m pip -v install -e apis/python[dev] -C "--build-option=--no-tiledb-deprecated"
        env:
          CC: clang
          CXX: clang
      - name: Show package versions
        run: python scripts/show-versions.py
      - name: Show XCode version
        run: clang --version
      - name: Obtain test data
        shell: bash
        run: |
          cd test
          rm -rf soco
          tar zxf soco.tgz
          cd ..
      - name: Run pytests for Python
        shell: bash
        # Setting PYTHONPATH ensures the tests load the in-tree source code under apis/python/src
        # instead of the copy we `pip install`ed to site-packages above. That's needed for the code
        # coverage analysis to work.
        run: PYTHONPATH=$(pwd)/apis/python/src python -m pytest --cov=apis/python/src --cov-report=xml apis/python/tests/test_dataframe.py -v --durations=20
      - name: Report coverage to Codecov
        uses: codecov/codecov-action@v3
        with:
          flags: python
