name: 'rm SOMA `Slice.__subclasscheck__`'
on:
  workflow_dispatch:
    inputs:
      runs-on:
        description: Host
        default: ubuntu-20.04
      tdbs-ref:
        description: TileDB-SOMA branch or tag to clone
        default: rw/tg
      soma-org:
        description: Org to clone single-cell-data/SOMA from
        type: choice
        default: ryan-williams
        options:
          - single-cell-data
          - ryan-williams
      soma-refs:
        description: single-cell-data/SOMA branch or tag to clone
        default: '"main", "slc"'
      soma-pretend-version:
        description: "Set the SOMA version, to satisfy TileDB-SOMA's pin (despite a shallow SOMA clone that's unable to compute a sensible version for itself)"
        default: '1.0.21'
      python-versions:
        description: Python versions to test
        default: '"3.9.4", "3.9.7", "3.9.10", "3.9.13", "3.9.19"'
      tests:
        description: Tests to run (under apis/python/)
        default: tests
jobs:
  job:
    strategy:
      matrix:
        soma-ref: ${{ fromJSON(format('[{0}]', inputs.soma-refs)) }}
        python-version: ${{ fromJSON(format('[{0}]', inputs.python-versions)) }}
      fail-fast: false
    name: ${{ matrix.python-version }} soma@${{ matrix.soma-ref }}
    runs-on: ${{ inputs.runs-on }}
    steps:
      - name: Checkout ${{ inputs.soma-org }}/SOMA@${{ matrix.soma-ref }}
        uses: actions/checkout@v4
        with:
          repository: ${{ inputs.soma-org }}/SOMA
          ref: ${{ matrix.soma-ref }}
          path: soma
      - name: Checkout TileDB-SOMA@${{ inputs.tdbs-ref }}
        uses: actions/checkout@v4
        with:
          repository: single-cell-data/TileDB-SOMA
          ref: ${{ inputs.tdbs-ref }}
          path: tdbs
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install SOMA, TileDB-SOMA
        env:
          SETUPTOOLS_SCM_PRETEND_VERSION_FOR_SOMACORE: ${{ inputs.soma-pretend-version }}
        run: pip install -e tdbs/apis/python[dev] -e soma
      - run: make data
        working-directory: tdbs
      - name: Run tests
        run: pytest --maxfail=10 ${{ inputs.tests }}
        working-directory: tdbs/apis/python
