name: Build and test
on:
  workflow_dispatch:
    inputs:
      ref:
        description: 'Branch or tag to build'
        default: 'main'
      reps:
        description: 'Number of times to repeat specific tests of interest'
        type: number
        default: 20
      tests:
        description: 'Specific testes to run repeatedly'
        default: 'test_dataframe.py test_experiment_query.py'
jobs:
  test:
    strategy:
      matrix:
        os: [ ubuntu-latest ]
        py: [ "3.8", "3.9", "3.10", "3.11" ]
      fail-fast: false
    name: ${{ matrix.os }} x Python ${{ matrix.py }}
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.py }}
      - uses: actions/checkout@v4
        with:
          repository: 'single-cell-data/TileDB-SOMA'
          fetch-depth: 0
      - run: git checkout ${{ github.event.inputs.ref }}
      - run: git log -1
      - run: make install build=Debug
      - run: make data
      - run: pip install -e apis/python[dev]
      - working-directory: apis/python
        run: |
          for t in ${{ inputs.tests }}; do
            for i in `seq ${{ inputs.reps }}`; do
              echo "Test $t, iteration $i:"
              pytest tests/$t &> $t.txt || cat $t.txt
            done
          done
      - name: Run all tests
        working-directory: apis/python
        run: pytest tests