name: 'pip install -e git+https'
on:
  workflow_dispatch:
    inputs:
      python-version:
        description: 'Python version'
        default: '3.11.8'
jobs:
  pip-install:
    name: '${{ matrix.runs-on }} ${{ matrix.ref }} pip install${{ matrix.editable }} git+https'
    strategy:
      fail-fast: false
      matrix:
        runs-on:
            - ubuntu-latest
            - macos-latest
        ref: [ main, ] # release-1.7, release-1.8, release-1.9 ]
        editable: [ ' -e', ] # '' ]
    runs-on: ${{ matrix.runs-on }}
    steps:
      - uses: actions/setup-python@v5
        with:
          python-version: ${{ inputs.python-version }}
      - run: |
          pip install${{ matrix.editable }} "git+https://github.com/single-cell-data/TileDB-SOMA.git@${{ matrix.ref }}#egg=tiledbsoma&subdirectory=apis/python/"
