# Placeholder Action on `main` branch, to be implemented/customized on
# individual branches, to repro specific issues.
name: gha.yml
on:
  workflow_dispatch:
    inputs:
      runs-on:
        description: Host
        type: choice
        options:
          - ubuntu-latest
          - macos-latest
          - macos-latest-xlarge
          - macos12
          - macos12-large
          - macos12-xlarge
          - macos14
          - windows-latest
jobs:
  job:
    runs-on: ${{ inputs.runs-on }}
    steps:
      - run: uname -m
