name: Repro spurious DoesNotExistError
on:
  workflow_dispatch:
    inputs:
      runs-on:
        description: Host
        type: choice
        default: ubuntu-latest
        options:
          - ubuntu-latest
          - macos-latest
          - macos-latest-xlarge
          - windows-latest
      python-version:
        description: Python version to use
        default: 3.11.8
      tdbs-version:
        description: TileDB-SOMA version to test
        default: 1.14.5
      uri:
        description: S3 URI to check
        default: s3://cellxgene-census-public-us-west-2/cell-census/2024-07-01/soma/census_data/homo_sapiens/ms/RNA/X/raw
env:
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
  AWS_REGION: us-west-2
jobs:
  job:
    name: Repro spurious DoesNotExistError
    runs-on: ${{ inputs.runs-on }}
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: ${{ inputs.python-version }}
      - run: pip install tiledbsoma==${{ inputs.tdbs-version }}
      - name: Test "aws s3 ls"
        run: aws s3 ls ${{ inputs.uri }}
      - name: Test tiledbsoma.open
        run: |
          cat open.py
          python open.py ${{ inputs.uri }}
      - name: Test Experiment.open
        run: |
          cat exp-open.py
          python exp-open.py ${{ inputs.uri }}
