name: 'Test `pip install -e` via git+https URL'
on:
  workflow_dispatch:
    inputs:
      python-version:
        description: 'Python version'
        default: '3.11.8'
      user-install:
        description: 'Install to user site'
        type: 'boolean'
        default: false
jobs:
  pip-install:
    name: '${{ matrix.ref }} ${{ matrix.editable }}: test `pip install` via git+https URL'
    runs-on: ubuntu-latest
    container: python:3.11.8
    strategy:
      fail-fast: false
      matrix:
        ref: [ main, release-1.7, release-1.8, release-1.9 ]
        editable: [ '-e', '' ]
    steps:
      - run: |
          apt-get update -y
          apt-get install -y cmake curl g++ git make ninja-build tar unzip zip
      - run: |
          pip install ${{ inputs.user-install && '--user' || '' }} ${{ matrix.editable }} 'git+https://github.com/single-cell-data/TileDB-SOMA.git@${{ matrix.ref }}#egg=tiledbsoma&subdirectory=apis/python/'
