name: Build and test
on:
  workflow_dispatch:
jobs:
  test:
    strategy:
      matrix:
        os: [ubuntu-latest]
        py: ["3.9", "3.10", "3.11", "3.12"]
      fail-fast: false
    name: ${{ matrix.os }} x Python ${{ matrix.py }}
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.py }}
      - uses: actions/checkout@v4
        with:
          repository: 'single-cell-data/TileDB-SOMA'
      - run: make install build=Debug
      - run: make data
      - run: pip install -e apis/python[dev]
      - run: |
          cd apis/python
          pytest tests