name: segfault repro
on:
  workflow_dispatch:
    inputs:
      runs-on:
        description: 'Select a runner ("macos-latest" = Intel, "macos-latest-xlarge" = M1)'
        default: 'macos-latest-xlarge'
        type: choice
        options:
          - macos-latest
          - macos-latest-xlarge
          - ubuntu-latest
          # - windows-latest
      ref:
        description: 'Branch or tag clone/install/test (leave blank to install latest version from PyPI)'
jobs:
  build:
    name: repro (${{ inputs.runs-on }})
    runs-on: ${{ inputs.runs-on }}
    steps:
      - name: 'Debug: `github` context'
        run: |
          echo "${{ toJSON(github.event) }}"
      - name: 'Test inputs.ref check'
        if: inputs.ref
        run: |
          echo "Ref: ${{ inputs.ref }}"
      - name: 'Test inputs.ref check 2'
        if: inputs.ref != ''
        run: |
          echo "Ref: ${{ inputs.ref }}"
      - uses: actions/checkout@v4
      - name: Clone TileDB-SOMA@${{ inputs.ref }}
        if: inputs.ref != ''
        uses: actions/checkout@v4
        with:
          repository: single-cell-data/TileDB-SOMA
          ref: ${{ inputs.ref }}
          path: tiledbsoma
      - uses: actions/setup-python@v5
        with:
          python-version: 3.11.8
      - run: |
          if [ -d tiledbsoma ]; then
            echo "Installing TileDB-SOMA from source"
            echo "1.9.0rc0" > tiledbsoma/apis/python/RELEASE-VERSION
            pip install -r requirements-local.txt
          else
            echo "Installing TileDB-SOMA from PyPI"
            pip install -r requirements-pypi.txt
          fi
      - run: pip list
      - name: Show TileDB/SOMA/OS versions
        run: |
          python -c 'import tiledbsoma; tiledbsoma.show_package_versions()'
          uname -a
      - name: 'Run without importing `tiledb` (always succeeds)'
        run: ./segfault-repro.py
      - name: 'Run with `import tiledb` before `import tiledbsoma` (sometimes segfaults)'
        env:
          IMPORT_TILEDB: 1
        run: |
          ./segfault-repro.py
          rv=$?
          echo "Exit code: $?"
          exit $rv
