name: Scratchwork
on:
  workflow_dispatch:
    inputs:
      runs-on:
        description: 'Github Actions runner'
        default: 'ubuntu-latest'
        type: choice
        options:
          - 'ubuntu-latest'
          - 'macos-latest'
          - 'windows-latest'
          - 'macos-latest-xlarge'
jobs:
  scratch:
    name: Test for VCPKG
    runs-on: ${{ inputs.runs-on }}
    steps:
      - run: env
      - run: uname -m
      - run: which vcpkg
      - run: echo $VCPKG_ROOT
