name: segfault repro
on:
  workflow_dispatch:
    inputs:
      runs-on:
        description: 'Select a runner ("macos-latest" = Intel, "macos-latest-xlarge" = M1)'
        default: 'macos-latest-xlarge'
        type: choice
        options:
          - macos-latest
          - macos-latest-xlarge
          - ubuntu-latest
          # - windows-latest
jobs:
  build:
    name: repro (${{ inputs.runs-on }}${{ matrix.import-tiledb && ', import-tiledb' || '' }})
    strategy:
      fail-fast: false
      matrix:
        import-tiledb: [ 'IMPORT_TILEDB', '' ]
    runs-on: ${{ inputs.runs-on }}
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: 3.11.8
          cache: pip
      - run: pip install -r requirements.txt
      - name: Show TileDB/SOMA versions
        run: python -c 'import tiledbsoma; tiledbsoma.show_package_versions()'
      - run: |
          python -X faulthandler segfault-repro.py
          rv=$?
          echo "Exit code: $?"
          exit $rv
        env:
          IMPORT_TILEDB: ${{ matrix.import-tiledb }}
